name: $(date:yyyyMMdd)$(rev:.r)
pool:
  name: Azure Pipelines
variables:
  - group: certbot-variables
trigger: none
stages:
- stage: createCertStage
  displayName: 'Create Certificate and Upload to KV'
  jobs:
  - job: createCertShellJob
    displayName: 'Shell: Install Certbot, Create Certificate and Upload to KV'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: 'Azure CLI certs/service-provider/renew-cert.sh'
      inputs:
        azureSubscription: CloudElementsSpn
        scriptType: bash
        scriptPath: 'certs/service-provider/renew-cert.sh'
      enabled: false
    - task: Bash@3
      displayName: 'Bash: Install Certbot, Create Certificate and Upload to KV'
      inputs:
        targetType: filePath
        filePath: './service-provider/renew-cert.sh'
      enabled: false
  - job: createCertPSJob
    displayName: 'Install Certbot, Create Certificate and Upload to KV'
    pool:
      vmImage: windows-2019
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens'
      inputs:
        rootDirectory: azure
        targetFiles: '*'
        tokenPattern: rm
        enableTelemetry: false
      enabled: true
    - task: AzurePowerShell@5
      displayName: 'PowerShell: Install Certbot, Create Certificate and Upload to KV'
      inputs:
        azureSubscription: 'CloudElementsSpn'
        ScriptPath: 'azure/az-renew-cert.ps1'
        azurePowerShellVersion: LatestVersion
      enabled: true
