name: $(date:yyyyMMdd)$(rev:.r)
pool:
  name: Azure Pipelines
variables:
  - group: certbot-variables
  - name: serviceConnection
    value: "CloudElementsSpn"
schedules:
- cron: "0 0 1 */2 *"
  displayName: string
  branches:
    include: 
    - main
  always: true
stages:
- stage: createCertStage
  displayName: 'Create Certificate and Upload to KV'
  jobs:
  - job: createCertShellJob
    displayName: 'Shell: Install Certbot, Create Certificate and Upload to KV'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens'
      inputs:
        rootDirectory: service-provider
        targetFiles: '*'
        tokenPattern: rm
        enableTelemetry: false
      enabled: false    
    - task: AzureCLI@2
      displayName: 'Azure CLI service-provider/renew-cert.sh'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptPath: 'service-provider/renew-cert.sh'
      enabled: false
  - job: createCertPSJob
    displayName: 'PowerShell: Install Certbot, Create Certificate and Upload to KV'
    pool:
      vmImage: windows-2019
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens'
      inputs:
        rootDirectory: azure
        targetFiles: '*'
        tokenPattern: rm
        enableTelemetry: false
      enabled: true
    - task: AzurePowerShell@5
      displayName: 'PowerShell: Install Certbot, Create Certificate and Upload to KV'
      inputs:
        azureSubscription: $(serviceConnection)
        ScriptPath: 'azure/az-renew-cert.ps1'
        azurePowerShellVersion: LatestVersion
      enabled: true
